services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - clickhouse_network

  kafka:
    image: confluentinc/cp-kafka:latest  # Используем cp-kafka, который совместим с cp-zookeeper
    ports:
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENER: kafka:9093   # Используем имя сервиса kafka
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INTERNAL: INSIDE_KAFKA
      KAFKA_LISTENER_INTERNAL: kafka:9093     # Исправляем на имя сервиса
      KAFKA_LISTENER_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
    networks:
      - clickhouse_network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9093"]
      interval: 10s
      retries: 5

  clickhouse:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"   # HTTP интерфейс
      - "9000:9000"   # TCP интерфейс
    environment:
      CLICKHOUSE_DB: default
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    networks:
      - clickhouse_network

  producer:
    build:
      context: ./producer
    depends_on:
      - kafka
    networks:
      - clickhouse_network
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka", "9093"]   # Проверка доступности Kafka
      interval: 10s
      retries: 5

  consumer:
    build:
      context: ./consumer
    depends_on:
      - kafka
      - clickhouse
    networks:
      - clickhouse_network
    healthcheck:
      test: ["CMD", "nc", "-z", "kafka", "9093"]   # Проверка доступности Kafka
      interval: 10s
      retries: 5

networks:
  clickhouse_network:
    driver: bridge

volumes:
  clickhouse_data:
